{"pageProps":{"metadata":{"title":"Python基礎文法 - 後期","curriculumId":"16c2297f-7a72-803f-872e-ef1fab8e273e","category":"後期","visibility":["基礎班","発展班"],"tags":["基礎班","Python"],"is_basic_curriculum":true,"id":"11"},"mdBlocks":[{"type":"paragraph","blockId":"16c2297f-7a72-81fe-86cb-fccb1ce0d422","parent":"今回はPythonの「例外処理」について説明します。","children":[]},{"blockId":"16c2297f-7a72-81ee-a370-da54cf94ad82","type":"heading_2","parent":"## 例外処理の基本：try、except","children":[]},{"blockId":"16c2297f-7a72-81d9-b8dd-d24b6273f9d1","type":"divider","parent":"---","children":[]},{"type":"paragraph","blockId":"16c2297f-7a72-81bb-8c9e-d005447c8f1e","parent":"Pythonの例外処理は、プログラムの実行中に発生するエラーを適切に扱い、プログラムのクラッシュを防ぐための仕組みです。","children":[]},{"type":"paragraph","blockId":"16c2297f-7a72-8119-a451-dfef67e5a561","parent":"例外処理を行うには、`try`、`except`を使います。","children":[]},{"blockId":"16c2297f-7a72-810d-a8f6-e0228d5b89a8","type":"callout","parent":"> ### 基本構文  \n>   \n> ```python  \n> try:  \n> \tエラーの可能性のある処理  \n> except 想定されるエラー:  \n> \tエラーが起こった場合の処理  \n> ```","children":[{"blockId":"16c2297f-7a72-8118-83df-e125a0576682","type":"heading_3","parent":"### 基本構文","children":[]},{"blockId":"16c2297f-7a72-8154-ac34-dfb467db27e1","type":"code","parent":"```python\ntry:\n\tエラーの可能性のある処理\nexcept 想定されるエラー:\n\tエラーが起こった場合の処理\n```","children":[]}]},{"type":"paragraph","blockId":"16c2297f-7a72-819d-90c1-f1364ad74a00","parent":"例えば、ゼロによる除算が行われると`ZeroDivisionError`というエラーが発生して処理が終了します。`try`、`except`を使うとそのようなエラーが起こった場合の処理を書くことができます。","children":[]},{"blockId":"16c2297f-7a72-819f-be9c-ee0ef324ec5f","type":"callout","parent":"> ### 例  \n>   \n> ```python  \n> a = 1  \n> b = 0  \n>   \n> try:  \n>     print(a / b)  \n> except ZeroDivisionError:  \n>     print('Error')  \n> ```","children":[{"blockId":"16c2297f-7a72-8153-9289-f3255138e2e7","type":"heading_3","parent":"### 例","children":[]},{"blockId":"16c2297f-7a72-819f-87f7-ce39f302e3e6","type":"code","parent":"```python\na = 1\nb = 0\n\ntry:\n    print(a / b)\nexcept ZeroDivisionError:\n    print('Error')\n```","children":[]}]},{"type":"paragraph","blockId":"16c2297f-7a72-8141-a98e-ce93a3abf3b1","parent":"この例では、`a`を`b`で割り算しています。`b`が`0`でない場合は割り算の答えが`print関数`で出力され、`b`が`0`だった場合は`Error`と出力されます。そして、このコードでは`b = 0`なので以下のように出力されます。","children":[]},{"blockId":"16c2297f-7a72-815e-a9ac-f8b8b9a4d6ba","type":"callout","parent":"> 出力  \n> ```bash  \n> Error  \n> ```","children":[{"blockId":"16c2297f-7a72-8195-936c-c70fb74be1c9","type":"code","parent":"```bash\nError\n```","children":[]}]},{"type":"paragraph","blockId":"16c2297f-7a72-81a5-9dab-c4147d0f3ba5","parent":"さらに、`except 例外名 as 変数名:`とすると、変数にエラーを格納して使用できる。変数名は任意の名前を指定できるが、`e`や`err`といった名前が使われることが多い。","children":[]},{"blockId":"16c2297f-7a72-8105-9758-cfd58d44e211","type":"callout","parent":"> ### エラーを変数に格納する  \n>   \n> ```python  \n> a = 1  \n> b = 0  \n>   \n> try:  \n>     print(a / b)  \n> **except ZeroDivisionError as e:  \n>     print('Error')  \n>     print(e)**  \n> ```","children":[{"blockId":"16c2297f-7a72-81d0-b97c-c04a9c13b92c","type":"heading_3","parent":"### エラーを変数に格納する","children":[]},{"blockId":"16c2297f-7a72-8130-95fa-eab3a074cec0","type":"code","parent":"```python\na = 1\nb = 0\n\ntry:\n    print(a / b)\n**except ZeroDivisionError as e:\n    print('Error')\n    print(e)**\n```","children":[]}]},{"type":"paragraph","blockId":"16c2297f-7a72-81c8-8171-fa13dfaaf224","parent":"このように書くと、以下のようにエラーが出力されます。","children":[]},{"blockId":"16c2297f-7a72-81fc-baca-ff5a122fef18","type":"callout","parent":"> 出力  \n> ```bash  \n> Error  \n> division by zero  \n> ```","children":[{"blockId":"16c2297f-7a72-8141-931f-ebec031b58d0","type":"code","parent":"```bash\nError\ndivision by zero\n```","children":[]}]},{"blockId":"16c2297f-7a72-8134-a491-c5b323fa6a72","type":"heading_2","parent":"## 正常終了時の処理：else","children":[]},{"blockId":"16c2297f-7a72-81ee-b52c-c908a9f1944f","type":"divider","parent":"---","children":[]},{"type":"paragraph","blockId":"16c2297f-7a72-8180-935f-c3b1ac430430","parent":"`try`節で例外が発生せず正常終了したあとに行う処理を`else`節に指定できる。例外が発生して`except`で例外処理をした場合は`else`節の処理は実行されません。","children":[]},{"blockId":"16c2297f-7a72-8182-9dab-c5ef95ea8d29","type":"callout","parent":"> ### 正常終了した場合の処理を書く  \n>   \n> ```python  \n> a = 20  \n> b = 5  \n>   \n> try:  \n>     result = a / b  \n> except ZeroDivisionError as e:  \n>     print('Error:', e)  \n> **else:  \n> \tprint(\"success:\", result)**  \n> ```","children":[{"blockId":"16c2297f-7a72-8132-bb9b-d1847a48e22e","type":"heading_3","parent":"### 正常終了した場合の処理を書く","children":[]},{"blockId":"16c2297f-7a72-8119-a7c3-d487532f8230","type":"code","parent":"```python\na = 20\nb = 5\n\ntry:\n    result = a / b\nexcept ZeroDivisionError as e:\n    print('Error:', e)\n**else:\n\tprint(\"success:\", result)**\n```","children":[]}]},{"type":"paragraph","blockId":"16c2297f-7a72-81ea-8b64-e2bd8f82e369","parent":"この場合、`try`節で`result = a / b`の処理がされます。`b=0`の場合は`except`節の処理が行われますが、今回は`b = 5`なので、`else`節の処理が行われ、以下のように出力されます。","children":[]},{"blockId":"16c2297f-7a72-81bc-9134-c87fe41a1d89","type":"callout","parent":"> 出力  \n> ```bash  \n> success: 4  \n> ```","children":[{"blockId":"16c2297f-7a72-819a-9e86-e4ba14595267","type":"code","parent":"```bash\nsuccess: 4\n```","children":[]}]},{"blockId":"16c2297f-7a72-8186-a139-cf2554877e43","type":"heading_2","parent":"## **終了時に常に行う処理： finally**","children":[]},{"blockId":"16c2297f-7a72-8139-8666-ef49cc5aa49a","type":"divider","parent":"---","children":[]},{"type":"paragraph","blockId":"16c2297f-7a72-81ce-9cf7-d0be22073466","parent":"例外が発生した場合もしなかった場合も常に最後に行う処理を`finally`節に指定できます。","children":[]},{"blockId":"16c2297f-7a72-81af-9951-f7753ff76a2e","type":"callout","parent":"> ### 終了時に常に行う処理を書く  \n>   \n> ```python  \n> a = 20  \n> b = 5  \n>   \n> try:  \n>     result = a / b  \n> except ZeroDivisionError as e:  \n>     print('Error:', e)  \n> else:  \n> \tprint(\"success:\", result)  \n> **finally:  \n> \tprint(\"finish\")**  \n> ```","children":[{"blockId":"16c2297f-7a72-8184-89d8-e0eaba1d60e9","type":"heading_3","parent":"### 終了時に常に行う処理を書く","children":[]},{"blockId":"16c2297f-7a72-81bc-84fe-d07436747086","type":"code","parent":"```python\na = 20\nb = 5\n\ntry:\n    result = a / b\nexcept ZeroDivisionError as e:\n    print('Error:', e)\nelse:\n\tprint(\"success:\", result)\n**finally:\n\tprint(\"finish\")**\n```","children":[]}]},{"type":"paragraph","blockId":"16c2297f-7a72-8165-a4fc-c5c5a73c09ae","parent":"この場合、`try`節で`result = a / b`の処理がされます。`b`の値が`0`か否かで`except`節の処理か`else`節の処理が行われますが、いずれの場合でも`finally`節の処理、`print(”finish”)` が行われます。","children":[]},{"type":"paragraph","blockId":"16c2297f-7a72-81b2-83bc-e35eefb06c3c","parent":"このコードの場合は`b=5`なので、以下のように出力されます。","children":[]},{"blockId":"16c2297f-7a72-816f-b70a-d2afe445cff9","type":"callout","parent":"> 出力  \n> ```bash  \n> success: 4  \n> finish  \n> ```","children":[{"blockId":"16c2297f-7a72-81c2-87cf-d93270f2be49","type":"code","parent":"```bash\nsuccess: 4\nfinish\n```","children":[]}]}],"pageNavs":[{"title":"Home","id":"/posts"},{"title":"基礎班カリキュラム","id":"/posts/course/basic"},{"title":"後期","id":"/posts/course/後期"},{"title":"Python基礎文法 - 後期","id":"/posts/curriculums/16c2297f-7a72-803f-872e-ef1fab8e273e/16c2297f-7a72-80b3-a867-f9e842f141de"}]},"__N_SSG":true}